version: 2.1

orbs:
  myruby:
    executors:
      ruby-3.1:
        docker:
          - image: cimg/ruby:3.1
    jobs:
      test-ruby-cmd:
        executor: ruby-3.1
        steps:
          - checkout
          - run:
              command: ruby -e "puts 123"
      test-ruby-shell:
        executor: ruby-3.1
        steps:
          - checkout
          - run:
              # inside the cimg/ruby image, the `ruby` runtime is available at /usr/local/bin/ruby
              # E.g.
              #  $ docker run --rm cimg/ruby:3.1 which ruby
              #  /usr/local/bin/ruby
              shell: /usr/local/bin/ruby
              command: |
                puts 123

jobs:
  test-python-shell:
    docker:
      - image: cimg/python:3.8
    steps:
      - run:
          shell: /usr/bin/python3
          command: |
            place = "World"
            print("Hello " + place + "!")

workflows:
  main:
    jobs:
      - myruby/test-ruby-shell
      - test-python-shell
