version: 2.1

jobs:
  python:
    environment:
      FOO: bar
    docker:
      - image: cimg/python:3.9
    steps:
      - run:
          name: print FOO
          shell: python
          command: |
            import os
            print(os.environ["FOO"])
  ruby:
    environment:
      FOO: bar
    docker:
      - image: cimg/ruby:2.7
    steps:
      - run:
          name: print FOO
          shell: ruby
          command: |
            puts ENV["FOO"]
  node:
    environment:
      FOO: bar
    docker:
      - image: cimg/node:lts
    steps:
      - run:
          name: print FOO
          shell: node
          command: |
            console.log(process.env.FOO);
  bash:
    environment:
      FOO: bar
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: print FOO
          command: |
            printenv FOO
  rscript:
    environment:
      FOO: bar
    docker:
      - image: rocker/tidyverse:latest
    steps:
      - run:
          name: print FOO
          shell: R -e
          command: |
            Sys.getenv("FOO")

workflows:
  taco-shells:
    jobs:
      - ruby
      - python
      - bash
      - node
      - rscript
