version: 2.1

orbs:
  myruby:
    jobs:
      test-ruby-cmd:
        docker:
          - image: cimg/ruby:3.1
        steps:
          - checkout
          - run:
              command: ruby -e "puts 123"
              
              
workflows:
  main:
    jobs:
      - myruby/test-ruby-cmd
