version: 2.1

jobs:
  bash:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: fail on purpose
          shell: '/bin/bash'
          command: |
            exit 1
      - run:
          name: halt
          shell: '/bin/bash -e'
          command: |
            circleci-agent step halt
          when: on_fail  

workflows:
  taco-shells:
    jobs:
      - bash
